name: build_parsed_article
on:
  workflow_dispatch:
  push:
    branches: ['ocr_patch', 'ocr_cache']

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  build_parsed_article:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'banned-historical-archives/ocr_helper'
          path: './ocr_helper'
          ref: 'main'
      - uses: actions/checkout@v4
        with:
          path: './ocr_config'
          ref: 'ocr_config'
      - uses: actions/checkout@v4
        with:
          path: './ocr_cache'
          ref: 'ocr_cache'
      - uses: actions/checkout@v4
        with:
          path: './ocr_patch'
          ref: 'ocr_patch'
      - uses: actions/checkout@v4
        with:
          path: './parsed_article'
          ref: 'parsed_article'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd ocr_helper && npm install && npm run build_parsed_article -- ../ocr_config ../ocr_cache ../ocr_patch ../parsed_article
      - run: git config --global http.postBuffer 2097152000
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"

      - name: Check for changes
        id: check_changes
        run: |
          cd parsed_article
          git status --porcelain
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            echo "changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected"
            echo "changes=true" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          cd ./parsed_article
          git add .
          git commit -m automation && git push
      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        if: steps.check_changes.outputs.changes == 'true'
        with:
          workflow: build_tags.yml
          ref: parsed_article
      - name: Invoke workflow
        if: steps.check_changes.outputs.changes == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          ref: master
          repo: banned-historical-archives/banned-historical-archives.github.io