name: build_tags
on:
  workflow_dispatch:
  push:
    branches: ['parsed_article']

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'banned-historical-archives/ocr_helper'
          path: './ocr_helper'
          ref: 'main'
      - uses: actions/checkout@v4
        with:
          path: './parsed_article'
          ref: 'parsed_article'
      - uses: actions/checkout@v4
        with:
          path: './tags'
          ref: 'tags'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd ocr_helper && npm install && npm run build_tags -- ../parsed_article ../tags
      - run: git config --global http.postBuffer 2097152000
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"

      - name: Check for changes
        id: check_changes
        run: |
          cd tags
          git status --porcelain
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            echo "::set-output name=changes::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes::true"
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          cd ./tags
          git add .
          git commit -m automation && git push